server:
  servlet:
    context-path:  #配置项目的访问路径
  port: 9528 #配置端口号
  address: 0.0.0.0
  minio:
    minio_url: http://47.116.196.3:9000
    minio_name: XiaoRan
    minio_pass: VirSep20
    bucketName: img
